FROM golang:1.25-alpine AS builder

# Install required tools
RUN apk add --no-cache git make

# Install Air for live reload
RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app

# Copy go.mod and download dependencies first (cache layer)
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the project
COPY . .

EXPOSE 8080

# Run Air with your config
CMD ["air", "-c", ".air.toml"]
